<?xml version="1.0" encoding="utf-8"?><Database Name="Leoni_Packaging_prod" Class="PackagingStoreDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WANGSONG-PC;Initial Catalog=Leoni_Packaging_prod;Persist Security Info=True;User ID=sa" SettingsObjectName="Brilliantech.Packaging.Store.Data.Properties.Settings" SettingsPropertyName="Leoni_Packaging_prodConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ContainerType" Member="ContainerType">
    <Type Name="ContainerType">
      <Column Name="containerID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="containerName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="containerDesc" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="long" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="width" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="height" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="reusable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="weight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="ContainerType_SinglePackage" Member="SinglePackage" ThisKey="containerID" OtherKey="containerID" Type="SinglePackage" />
    </Type>
  </Table>
  <Table Name="dbo.WorkStation" Member="WorkStation">
    <Type Name="WorkStation">
      <Column Name="wrkStnID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="wrkStnName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="prodLineID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="WorkStation_SinglePackage" Member="SinglePackage" ThisKey="wrkStnID" OtherKey="wrkstnID" Type="SinglePackage" />
    </Type>
  </Table>
  <Table Name="dbo.PackageItem" Member="PackageItem">
    <Type Name="PackageItem">
      <Column Name="itemUid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="itemSeq" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TNr" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="packagingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="packageID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="SinglePackage_PackageItem" Member="SinglePackage" ThisKey="packageID" OtherKey="packageID" Type="SinglePackage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Part" Member="Part">
    <Type Name="Part">
      <Column Name="partNr" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="partName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="customerPartNr" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="projectID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="customerPCR" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Part_SinglePackage" Member="SinglePackage" ThisKey="partNr" OtherKey="partNr" Type="SinglePackage" />
      <Association Name="Project_Part" Member="Project" ThisKey="projectID" OtherKey="projectID" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Project" Member="Project">
    <Type Name="Project">
      <Column Name="projectID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="projectName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Project_Part" Member="Part" ThisKey="projectID" OtherKey="projectID" Type="Part" />
    </Type>
  </Table>
  <Table Name="dbo.SinglePackage" Member="SinglePackage">
    <Type Name="SinglePackage">
      <Column Name="packageID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="capa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="containerID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="planedDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="partNr" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="wrkstnID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="SinglePackage_PackageItem" Member="PackageItem" ThisKey="packageID" OtherKey="packageID" Type="PackageItem" />
      <Association Name="SinglePackage_TrayItem" Member="TrayItem" ThisKey="packageID" OtherKey="packageId" Type="TrayItem" />
      <Association Name="ContainerType_SinglePackage" Member="ContainerType" ThisKey="containerID" OtherKey="containerID" Type="ContainerType" IsForeignKey="true" />
      <Association Name="Part_SinglePackage" Member="Part" ThisKey="partNr" OtherKey="partNr" Type="Part" IsForeignKey="true" />
      <Association Name="WorkStation_SinglePackage" Member="WorkStation" ThisKey="wrkstnID" OtherKey="wrkStnID" Type="WorkStation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrayItem" Member="TrayItem">
    <Type Name="TrayItem">
      <Column Name="itemId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="packageId" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="trayId" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="SinglePackage_TrayItem" Member="SinglePackage" ThisKey="packageId" OtherKey="packageID" Type="SinglePackage" IsForeignKey="true" />
      <Association Name="Trays_TrayItem" Member="Trays" ThisKey="trayId" OtherKey="trayId" Type="Trays" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrayPackView" Member="TrayPackView">
    <Type Name="TrayPackView">
      <Column Name="packageID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="capa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spsatus" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="partNr" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="trayId" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="tstatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="position" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="warehouse" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="createTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="customerPartNr" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.HandSinglePackage" Member="HandSinglePackage">
    <Type Name="HandSinglePackage">
      <Column Name="packageID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="capa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="partNr" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="projectID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cusPartNr" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="createDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trays" Member="Trays">
    <Type Name="Trays">
      <Column Name="trayId" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="createTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="warehouse" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="position" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="sync" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Trays_TrayItem" Member="TrayItem" ThisKey="trayId" OtherKey="trayId" Type="TrayItem" />
    </Type>
  </Table>
</Database>