'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace PackagingService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SinglePackage", [Namespace]:="http://schemas.datacontract.org/2004/07/Brilliantech.Packaging.Data"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SinglePackage
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private packageIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private capaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private statusField As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private containerIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private planedDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private partNrField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private wrkstnIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PackageItemsField() As PackagingService.PackageItem
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property packageID() As String
            Get
                Return Me.packageIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.packageIDField, value) <> true) Then
                    Me.packageIDField = value
                    Me.RaisePropertyChanged("packageID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public Property capa() As Integer
            Get
                Return Me.capaField
            End Get
            Set
                If (Me.capaField.Equals(value) <> true) Then
                    Me.capaField = value
                    Me.RaisePropertyChanged("capa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public Property status() As Byte
            Get
                Return Me.statusField
            End Get
            Set
                If (Me.statusField.Equals(value) <> true) Then
                    Me.statusField = value
                    Me.RaisePropertyChanged("status")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public Property containerID() As String
            Get
                Return Me.containerIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.containerIDField, value) <> true) Then
                    Me.containerIDField = value
                    Me.RaisePropertyChanged("containerID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Property planedDate() As Date
            Get
                Return Me.planedDateField
            End Get
            Set
                If (Me.planedDateField.Equals(value) <> true) Then
                    Me.planedDateField = value
                    Me.RaisePropertyChanged("planedDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public Property partNr() As String
            Get
                Return Me.partNrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.partNrField, value) <> true) Then
                    Me.partNrField = value
                    Me.RaisePropertyChanged("partNr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public Property wrkstnID() As String
            Get
                Return Me.wrkstnIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.wrkstnIDField, value) <> true) Then
                    Me.wrkstnIDField = value
                    Me.RaisePropertyChanged("wrkstnID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property PackageItems() As PackagingService.PackageItem()
            Get
                Return Me.PackageItemsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PackageItemsField, value) <> true) Then
                    Me.PackageItemsField = value
                    Me.RaisePropertyChanged("PackageItems")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PackageItem", [Namespace]:="http://schemas.datacontract.org/2004/07/Brilliantech.Packaging.Data"),  _
     System.SerializableAttribute()>  _
    Partial Public Class PackageItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private itemUidField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private itemSeqField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TNrField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private packagingTimeField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private packageIDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property itemUid() As Integer
            Get
                Return Me.itemUidField
            End Get
            Set
                If (Me.itemUidField.Equals(value) <> true) Then
                    Me.itemUidField = value
                    Me.RaisePropertyChanged("itemUid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public Property itemSeq() As Integer
            Get
                Return Me.itemSeqField
            End Get
            Set
                If (Me.itemSeqField.Equals(value) <> true) Then
                    Me.itemSeqField = value
                    Me.RaisePropertyChanged("itemSeq")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public Property TNr() As String
            Get
                Return Me.TNrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TNrField, value) <> true) Then
                    Me.TNrField = value
                    Me.RaisePropertyChanged("TNr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public Property packagingTime() As Date
            Get
                Return Me.packagingTimeField
            End Get
            Set
                If (Me.packagingTimeField.Equals(value) <> true) Then
                    Me.packagingTimeField = value
                    Me.RaisePropertyChanged("packagingTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Property packageID() As String
            Get
                Return Me.packageIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.packageIDField, value) <> true) Then
                    Me.packageIDField = value
                    Me.RaisePropertyChanged("packageID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ServiceMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Brilliantech.Framework.WCF.Data"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ServiceMessage
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReturnedMessageField() As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReturnedResultField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReturnedMessage() As String()
            Get
                Return Me.ReturnedMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReturnedMessageField, value) <> true) Then
                    Me.ReturnedMessageField = value
                    Me.RaisePropertyChanged("ReturnedMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReturnedResult() As Boolean
            Get
                Return Me.ReturnedResultField
            End Get
            Set
                If (Me.ReturnedResultField.Equals(value) <> true) Then
                    Me.ReturnedResultField = value
                    Me.RaisePropertyChanged("ReturnedResult")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="PackagingService.IPackProcess")>  _
    Public Interface IPackProcess
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/Create", ReplyAction:="http://tempuri.org/IPackProcess/CreateResponse")>  _
        Function Create(ByVal package As PackagingService.SinglePackage) As PackagingService.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/Scrap", ReplyAction:="http://tempuri.org/IPackProcess/ScrapResponse")>  _
        Function Scrap(ByVal packageID As String) As PackagingService.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/AddItem", ReplyAction:="http://tempuri.org/IPackProcess/AddItemResponse")>  _
        Function AddItem(ByVal packageID As String, ByVal barcodeStr As String) As PackagingService.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/BeginProcess", ReplyAction:="http://tempuri.org/IPackProcess/BeginProcessResponse")>  _
        Function BeginProcess(ByVal packageID As String, ByVal wrkStnID As String) As PackagingService.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/EndProcess", ReplyAction:="http://tempuri.org/IPackProcess/EndProcessResponse")>  _
        Function EndProcess(ByVal packageID As String) As PackagingService.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/SuspendProcess", ReplyAction:="http://tempuri.org/IPackProcess/SuspendProcessResponse")>  _
        Function SuspendProcess(ByVal packageID As String) As PackagingService.ServiceMessage
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IPackProcessChannel
        Inherits PackagingService.IPackProcess, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PackProcessClient
        Inherits System.ServiceModel.ClientBase(Of PackagingService.IPackProcess)
        Implements PackagingService.IPackProcess
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Create(ByVal package As PackagingService.SinglePackage) As PackagingService.ServiceMessage Implements PackagingService.IPackProcess.Create
            Return MyBase.Channel.Create(package)
        End Function
        
        Public Function Scrap(ByVal packageID As String) As PackagingService.ServiceMessage Implements PackagingService.IPackProcess.Scrap
            Return MyBase.Channel.Scrap(packageID)
        End Function
        
        Public Function AddItem(ByVal packageID As String, ByVal barcodeStr As String) As PackagingService.ServiceMessage Implements PackagingService.IPackProcess.AddItem
            Return MyBase.Channel.AddItem(packageID, barcodeStr)
        End Function
        
        Public Function BeginProcess(ByVal packageID As String, ByVal wrkStnID As String) As PackagingService.ServiceMessage Implements PackagingService.IPackProcess.BeginProcess
            Return MyBase.Channel.BeginProcess(packageID, wrkStnID)
        End Function
        
        Public Function EndProcess(ByVal packageID As String) As PackagingService.ServiceMessage Implements PackagingService.IPackProcess.EndProcess
            Return MyBase.Channel.EndProcess(packageID)
        End Function
        
        Public Function SuspendProcess(ByVal packageID As String) As PackagingService.ServiceMessage Implements PackagingService.IPackProcess.SuspendProcess
            Return MyBase.Channel.SuspendProcess(packageID)
        End Function
    End Class
End Namespace
