'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.1
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace LabelDataService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PrintDataMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Brilliantech.Packaging.WS"),  _
     System.SerializableAttribute()>  _
    Partial Public Class PrintDataMessage
        Inherits Brilliantech.Framework.WCF.Data.ServiceMessage
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PrintTaskField() As Brilliantech.ReportGenConnector.PrintTask
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PrintTask() As Brilliantech.ReportGenConnector.PrintTask()
            Get
                Return Me.PrintTaskField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PrintTaskField, value) <> true) Then
                    Me.PrintTaskField = value
                    Me.RaisePropertyChanged("PrintTask")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="LabelDataService.IPrintService")>  _
    Public Interface IPrintService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrintService/PrintCloseLabel", ReplyAction:="http://tempuri.org/IPrintService/PrintCloseLabelResponse")>  _
        Function PrintCloseLabel(ByVal packageID As String) As LabelDataService.PrintDataMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrintService/PrintUnfullLabel", ReplyAction:="http://tempuri.org/IPrintService/PrintUnfullLabelResponse")>  _
        Function PrintUnfullLabel(ByVal packageID As String) As LabelDataService.PrintDataMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrintService/PrintOpenLabel", ReplyAction:="http://tempuri.org/IPrintService/PrintOpenLabelResponse")>  _
        Function PrintOpenLabel(ByVal packageID As String) As LabelDataService.PrintDataMessage
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IPrintServiceChannel
        Inherits LabelDataService.IPrintService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PrintServiceClient
        Inherits System.ServiceModel.ClientBase(Of LabelDataService.IPrintService)
        Implements LabelDataService.IPrintService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function PrintCloseLabel(ByVal packageID As String) As LabelDataService.PrintDataMessage Implements LabelDataService.IPrintService.PrintCloseLabel
            Return MyBase.Channel.PrintCloseLabel(packageID)
        End Function
        
        Public Function PrintUnfullLabel(ByVal packageID As String) As LabelDataService.PrintDataMessage Implements LabelDataService.IPrintService.PrintUnfullLabel
            Return MyBase.Channel.PrintUnfullLabel(packageID)
        End Function
        
        Public Function PrintOpenLabel(ByVal packageID As String) As LabelDataService.PrintDataMessage Implements LabelDataService.IPrintService.PrintOpenLabel
            Return MyBase.Channel.PrintOpenLabel(packageID)
        End Function
    End Class
End Namespace
