'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.1
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace PackService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="PackService.IPackProcess")>  _
    Public Interface IPackProcess
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/FindByID", ReplyAction:="http://tempuri.org/IPackProcess/FindByIDResponse")>  _
        Function FindByID(ByVal id As String) As Brilliantech.Packaging.WS.PackageMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/FindByItem", ReplyAction:="http://tempuri.org/IPackProcess/FindByItemResponse")>  _
        Function FindByItem(ByVal id As String) As Brilliantech.Packaging.WS.PackageMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/CountItem", ReplyAction:="http://tempuri.org/IPackProcess/CountItemResponse")>  _
        Function CountItem(ByVal id As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/Create", ReplyAction:="http://tempuri.org/IPackProcess/CreateResponse")>  _
        Function Create(ByVal package As Brilliantech.Packaging.Data.SinglePackage, ByVal mode As Brilliantech.Packaging.Data.PackagingType) As Brilliantech.Packaging.WS.PackageMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/Scrap", ReplyAction:="http://tempuri.org/IPackProcess/ScrapResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Brilliantech.Packaging.WS.PackageMessage))>  _
        Function Scrap(ByVal packageID As String) As Brilliantech.Framework.WCF.Data.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/AddItem", ReplyAction:="http://tempuri.org/IPackProcess/AddItemResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Brilliantech.Packaging.WS.PackageMessage))>  _
        Function AddItem(ByVal packageID As String, ByVal barcodeStr As String) As Brilliantech.Framework.WCF.Data.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/Recover", ReplyAction:="http://tempuri.org/IPackProcess/RecoverResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Brilliantech.Packaging.WS.PackageMessage))>  _
        Function Recover(ByVal packageID As String) As Brilliantech.Framework.WCF.Data.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/BeginProcess", ReplyAction:="http://tempuri.org/IPackProcess/BeginProcessResponse")>  _
        Function BeginProcess(ByVal packageID As String, ByVal wrkStnID As String, ByVal mode As Brilliantech.Packaging.Data.PackagingType) As Brilliantech.Packaging.WS.PackageMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/EndProcess", ReplyAction:="http://tempuri.org/IPackProcess/EndProcessResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Brilliantech.Packaging.WS.PackageMessage))>  _
        Function EndProcess(ByVal packageID As String) As Brilliantech.Framework.WCF.Data.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/SuspendProcess", ReplyAction:="http://tempuri.org/IPackProcess/SuspendProcessResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Brilliantech.Packaging.WS.PackageMessage))>  _
        Function SuspendProcess(ByVal packageID As String) As Brilliantech.Framework.WCF.Data.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/GetUnfull", ReplyAction:="http://tempuri.org/IPackProcess/GetUnfullResponse")>  _
        Function GetUnfull(ByVal packageId As String, ByVal wrkStnId As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/CancelPackaging", ReplyAction:="http://tempuri.org/IPackProcess/CancelPackagingResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Brilliantech.Packaging.WS.PackageMessage))>  _
        Function CancelPackaging(ByVal packageId As String) As Brilliantech.Framework.WCF.Data.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/GetPackageInfos", ReplyAction:="http://tempuri.org/IPackProcess/GetPackageInfosResponse")>  _
        Function GetPackageInfos(ByVal pid As String, ByVal wrkstnr As String, ByVal tnr As String, ByVal partnr As String, ByVal status As Integer, ByVal fromDate As Date, ByVal toDate As Date) As Brilliantech.Packaging.Data.FullPackageInfo()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/GetItemsByPackageId", ReplyAction:="http://tempuri.org/IPackProcess/GetItemsByPackageIdResponse")>  _
        Function GetItemsByPackageId(ByVal pId As String) As Brilliantech.Packaging.Data.PackageItem()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/GetPackageStatus", ReplyAction:="http://tempuri.org/IPackProcess/GetPackageStatusResponse")>  _
        Function GetPackageStatus() As Brilliantech.Packaging.WS.EnumObject()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/GetValidateItemsByPackageId", ReplyAction:="http://tempuri.org/IPackProcess/GetValidateItemsByPackageIdResponse")>  _
        Function GetValidateItemsByPackageId(ByVal packageId As String) As Brilliantech.Packaging.Data.CustomValidate()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/GetValidateItemsByPartAndWrkst", ReplyAction:="http://tempuri.org/IPackProcess/GetValidateItemsByPartAndWrkstResponse")>  _
        Function GetValidateItemsByPartAndWrkst(ByVal partNr As String, ByVal wrkstnr As String) As Brilliantech.Packaging.Data.CustomValidate()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/WorkstationExists", ReplyAction:="http://tempuri.org/IPackProcess/WorkstationExistsResponse")>  _
        Function WorkstationExists(ByVal wrkstnr As String) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IPackProcessChannel
        Inherits PackService.IPackProcess, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PackProcessClient
        Inherits System.ServiceModel.ClientBase(Of PackService.IPackProcess)
        Implements PackService.IPackProcess
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function FindByID(ByVal id As String) As Brilliantech.Packaging.WS.PackageMessage Implements PackService.IPackProcess.FindByID
            Return MyBase.Channel.FindByID(id)
        End Function
        
        Public Function FindByItem(ByVal id As String) As Brilliantech.Packaging.WS.PackageMessage Implements PackService.IPackProcess.FindByItem
            Return MyBase.Channel.FindByItem(id)
        End Function
        
        Public Function CountItem(ByVal id As String) As Integer Implements PackService.IPackProcess.CountItem
            Return MyBase.Channel.CountItem(id)
        End Function
        
        Public Function Create(ByVal package As Brilliantech.Packaging.Data.SinglePackage, ByVal mode As Brilliantech.Packaging.Data.PackagingType) As Brilliantech.Packaging.WS.PackageMessage Implements PackService.IPackProcess.Create
            Return MyBase.Channel.Create(package, mode)
        End Function
        
        Public Function Scrap(ByVal packageID As String) As Brilliantech.Framework.WCF.Data.ServiceMessage Implements PackService.IPackProcess.Scrap
            Return MyBase.Channel.Scrap(packageID)
        End Function
        
        Public Function AddItem(ByVal packageID As String, ByVal barcodeStr As String) As Brilliantech.Framework.WCF.Data.ServiceMessage Implements PackService.IPackProcess.AddItem
            Return MyBase.Channel.AddItem(packageID, barcodeStr)
        End Function
        
        Public Function Recover(ByVal packageID As String) As Brilliantech.Framework.WCF.Data.ServiceMessage Implements PackService.IPackProcess.Recover
            Return MyBase.Channel.Recover(packageID)
        End Function
        
        Public Function BeginProcess(ByVal packageID As String, ByVal wrkStnID As String, ByVal mode As Brilliantech.Packaging.Data.PackagingType) As Brilliantech.Packaging.WS.PackageMessage Implements PackService.IPackProcess.BeginProcess
            Return MyBase.Channel.BeginProcess(packageID, wrkStnID, mode)
        End Function
        
        Public Function EndProcess(ByVal packageID As String) As Brilliantech.Framework.WCF.Data.ServiceMessage Implements PackService.IPackProcess.EndProcess
            Return MyBase.Channel.EndProcess(packageID)
        End Function
        
        Public Function SuspendProcess(ByVal packageID As String) As Brilliantech.Framework.WCF.Data.ServiceMessage Implements PackService.IPackProcess.SuspendProcess
            Return MyBase.Channel.SuspendProcess(packageID)
        End Function
        
        Public Function GetUnfull(ByVal packageId As String, ByVal wrkStnId As String) As String Implements PackService.IPackProcess.GetUnfull
            Return MyBase.Channel.GetUnfull(packageId, wrkStnId)
        End Function
        
        Public Function CancelPackaging(ByVal packageId As String) As Brilliantech.Framework.WCF.Data.ServiceMessage Implements PackService.IPackProcess.CancelPackaging
            Return MyBase.Channel.CancelPackaging(packageId)
        End Function
        
        Public Function GetPackageInfos(ByVal pid As String, ByVal wrkstnr As String, ByVal tnr As String, ByVal partnr As String, ByVal status As Integer, ByVal fromDate As Date, ByVal toDate As Date) As Brilliantech.Packaging.Data.FullPackageInfo() Implements PackService.IPackProcess.GetPackageInfos
            Return MyBase.Channel.GetPackageInfos(pid, wrkstnr, tnr, partnr, status, fromDate, toDate)
        End Function
        
        Public Function GetItemsByPackageId(ByVal pId As String) As Brilliantech.Packaging.Data.PackageItem() Implements PackService.IPackProcess.GetItemsByPackageId
            Return MyBase.Channel.GetItemsByPackageId(pId)
        End Function
        
        Public Function GetPackageStatus() As Brilliantech.Packaging.WS.EnumObject() Implements PackService.IPackProcess.GetPackageStatus
            Return MyBase.Channel.GetPackageStatus
        End Function
        
        Public Function GetValidateItemsByPackageId(ByVal packageId As String) As Brilliantech.Packaging.Data.CustomValidate() Implements PackService.IPackProcess.GetValidateItemsByPackageId
            Return MyBase.Channel.GetValidateItemsByPackageId(packageId)
        End Function
        
        Public Function GetValidateItemsByPartAndWrkst(ByVal partNr As String, ByVal wrkstnr As String) As Brilliantech.Packaging.Data.CustomValidate() Implements PackService.IPackProcess.GetValidateItemsByPartAndWrkst
            Return MyBase.Channel.GetValidateItemsByPartAndWrkst(partNr, wrkstnr)
        End Function
        
        Public Function WorkstationExists(ByVal wrkstnr As String) As Boolean Implements PackService.IPackProcess.WorkstationExists
            Return MyBase.Channel.WorkstationExists(wrkstnr)
        End Function
    End Class
End Namespace
