'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.1
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace packSvc
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ServiceMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Brilliantech.Framework.WCF.Data"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(packSvc.PackageMessage))>  _
    Partial Public Class ServiceMessage
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReturnedMessageField() As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReturnedResultField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReturnedMessage() As String()
            Get
                Return Me.ReturnedMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReturnedMessageField, value) <> true) Then
                    Me.ReturnedMessageField = value
                    Me.RaisePropertyChanged("ReturnedMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReturnedResult() As Boolean
            Get
                Return Me.ReturnedResultField
            End Get
            Set
                If (Me.ReturnedResultField.Equals(value) <> true) Then
                    Me.ReturnedResultField = value
                    Me.RaisePropertyChanged("ReturnedResult")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PackageMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Brilliantech.Packaging.WS"),  _
     System.SerializableAttribute()>  _
    Partial Public Class PackageMessage
        Inherits packSvc.ServiceMessage
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PackageField As Brilliantech.Packaging.Data.SinglePackage
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Package() As Brilliantech.Packaging.Data.SinglePackage
            Get
                Return Me.PackageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PackageField, value) <> true) Then
                    Me.PackageField = value
                    Me.RaisePropertyChanged("Package")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EnumObject", [Namespace]:="http://schemas.datacontract.org/2004/07/Brilliantech.Packaging.WS"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(packSvc.PackageMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(packSvc.EnumObject())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(packSvc.ServiceMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(String())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Brilliantech.Packaging.Data.SinglePackage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Brilliantech.Packaging.Data.TrayItem())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Brilliantech.Packaging.Data.TrayItem)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Brilliantech.Packaging.Data.PackageItem())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Brilliantech.Packaging.Data.PackageItem)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Brilliantech.Packaging.Data.PackagingType)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Brilliantech.Packaging.Data.FullPackageInfo())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Brilliantech.Packaging.Data.FullPackageInfo)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Brilliantech.Packaging.Data.PackageStatus)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Brilliantech.Packaging.Data.CustomValidate())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Brilliantech.Packaging.Data.CustomValidate))>  _
    Partial Public Class EnumObject
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As Object
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EnumKeyField As Object
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EnumValueField As Object
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As Object
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EnumKey() As Object
            Get
                Return Me.EnumKeyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EnumKeyField, value) <> true) Then
                    Me.EnumKeyField = value
                    Me.RaisePropertyChanged("EnumKey")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EnumValue() As Object
            Get
                Return Me.EnumValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EnumValueField, value) <> true) Then
                    Me.EnumValueField = value
                    Me.RaisePropertyChanged("EnumValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="packSvc.IPackProcess")>  _
    Public Interface IPackProcess
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/FindByID", ReplyAction:="http://tempuri.org/IPackProcess/FindByIDResponse")>  _
        Function FindByID(ByVal id As String) As packSvc.PackageMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/FindByItem", ReplyAction:="http://tempuri.org/IPackProcess/FindByItemResponse")>  _
        Function FindByItem(ByVal id As String) As packSvc.PackageMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/CountItem", ReplyAction:="http://tempuri.org/IPackProcess/CountItemResponse")>  _
        Function CountItem(ByVal id As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/Create", ReplyAction:="http://tempuri.org/IPackProcess/CreateResponse")>  _
        Function Create(ByVal package As Brilliantech.Packaging.Data.SinglePackage, ByVal mode As Brilliantech.Packaging.Data.PackagingType) As packSvc.PackageMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/Scrap", ReplyAction:="http://tempuri.org/IPackProcess/ScrapResponse")>  _
        Function Scrap(ByVal packageID As String) As packSvc.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/AddItem", ReplyAction:="http://tempuri.org/IPackProcess/AddItemResponse")>  _
        Function AddItem(ByVal packageID As String, ByVal barcodeStr As String) As packSvc.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/Recover", ReplyAction:="http://tempuri.org/IPackProcess/RecoverResponse")>  _
        Function Recover(ByVal packageID As String) As packSvc.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/BeginProcess", ReplyAction:="http://tempuri.org/IPackProcess/BeginProcessResponse")>  _
        Function BeginProcess(ByVal packageID As String, ByVal wrkStnID As String, ByVal mode As Brilliantech.Packaging.Data.PackagingType) As packSvc.PackageMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/EndProcess", ReplyAction:="http://tempuri.org/IPackProcess/EndProcessResponse")>  _
        Function EndProcess(ByVal packageID As String) As packSvc.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/SuspendProcess", ReplyAction:="http://tempuri.org/IPackProcess/SuspendProcessResponse")>  _
        Function SuspendProcess(ByVal packageID As String) As packSvc.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/GetUnfull", ReplyAction:="http://tempuri.org/IPackProcess/GetUnfullResponse")>  _
        Function GetUnfull(ByVal packageId As String, ByVal wrkStnId As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/CancelPackaging", ReplyAction:="http://tempuri.org/IPackProcess/CancelPackagingResponse")>  _
        Function CancelPackaging(ByVal packageId As String) As packSvc.ServiceMessage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/GetPackageInfos", ReplyAction:="http://tempuri.org/IPackProcess/GetPackageInfosResponse")>  _
        Function GetPackageInfos(ByVal pid As String, ByVal wrkstnr As String, ByVal tnr As String, ByVal partnr As String, ByVal status As Integer, ByVal fromDate As Date, ByVal toDate As Date) As Brilliantech.Packaging.Data.FullPackageInfo()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/GetItemsByPackageId", ReplyAction:="http://tempuri.org/IPackProcess/GetItemsByPackageIdResponse")>  _
        Function GetItemsByPackageId(ByVal pId As String) As Brilliantech.Packaging.Data.PackageItem()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/GetPackageStatus", ReplyAction:="http://tempuri.org/IPackProcess/GetPackageStatusResponse")>  _
        Function GetPackageStatus() As packSvc.EnumObject()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/GetValidateItemsByPackageId", ReplyAction:="http://tempuri.org/IPackProcess/GetValidateItemsByPackageIdResponse")>  _
        Function GetValidateItemsByPackageId(ByVal packageId As String) As Brilliantech.Packaging.Data.CustomValidate()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/GetValidateItemsByPartAndWrkst", ReplyAction:="http://tempuri.org/IPackProcess/GetValidateItemsByPartAndWrkstResponse")>  _
        Function GetValidateItemsByPartAndWrkst(ByVal partNr As String, ByVal wrkstnr As String) As Brilliantech.Packaging.Data.CustomValidate()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/WorkstationExists", ReplyAction:="http://tempuri.org/IPackProcess/WorkstationExistsResponse")>  _
        Function WorkstationExists(ByVal wrkstnr As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPackProcess/ModifyPackage", ReplyAction:="http://tempuri.org/IPackProcess/ModifyPackageResponse")>  _
        Function ModifyPackage(ByVal pack As Brilliantech.Packaging.Data.SinglePackage) As packSvc.ServiceMessage
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IPackProcessChannel
        Inherits packSvc.IPackProcess, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PackProcessClient
        Inherits System.ServiceModel.ClientBase(Of packSvc.IPackProcess)
        Implements packSvc.IPackProcess
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function FindByID(ByVal id As String) As packSvc.PackageMessage Implements packSvc.IPackProcess.FindByID
            Return MyBase.Channel.FindByID(id)
        End Function
        
        Public Function FindByItem(ByVal id As String) As packSvc.PackageMessage Implements packSvc.IPackProcess.FindByItem
            Return MyBase.Channel.FindByItem(id)
        End Function
        
        Public Function CountItem(ByVal id As String) As Integer Implements packSvc.IPackProcess.CountItem
            Return MyBase.Channel.CountItem(id)
        End Function
        
        Public Function Create(ByVal package As Brilliantech.Packaging.Data.SinglePackage, ByVal mode As Brilliantech.Packaging.Data.PackagingType) As packSvc.PackageMessage Implements packSvc.IPackProcess.Create
            Return MyBase.Channel.Create(package, mode)
        End Function
        
        Public Function Scrap(ByVal packageID As String) As packSvc.ServiceMessage Implements packSvc.IPackProcess.Scrap
            Return MyBase.Channel.Scrap(packageID)
        End Function
        
        Public Function AddItem(ByVal packageID As String, ByVal barcodeStr As String) As packSvc.ServiceMessage Implements packSvc.IPackProcess.AddItem
            Return MyBase.Channel.AddItem(packageID, barcodeStr)
        End Function
        
        Public Function Recover(ByVal packageID As String) As packSvc.ServiceMessage Implements packSvc.IPackProcess.Recover
            Return MyBase.Channel.Recover(packageID)
        End Function
        
        Public Function BeginProcess(ByVal packageID As String, ByVal wrkStnID As String, ByVal mode As Brilliantech.Packaging.Data.PackagingType) As packSvc.PackageMessage Implements packSvc.IPackProcess.BeginProcess
            Return MyBase.Channel.BeginProcess(packageID, wrkStnID, mode)
        End Function
        
        Public Function EndProcess(ByVal packageID As String) As packSvc.ServiceMessage Implements packSvc.IPackProcess.EndProcess
            Return MyBase.Channel.EndProcess(packageID)
        End Function
        
        Public Function SuspendProcess(ByVal packageID As String) As packSvc.ServiceMessage Implements packSvc.IPackProcess.SuspendProcess
            Return MyBase.Channel.SuspendProcess(packageID)
        End Function
        
        Public Function GetUnfull(ByVal packageId As String, ByVal wrkStnId As String) As String Implements packSvc.IPackProcess.GetUnfull
            Return MyBase.Channel.GetUnfull(packageId, wrkStnId)
        End Function
        
        Public Function CancelPackaging(ByVal packageId As String) As packSvc.ServiceMessage Implements packSvc.IPackProcess.CancelPackaging
            Return MyBase.Channel.CancelPackaging(packageId)
        End Function
        
        Public Function GetPackageInfos(ByVal pid As String, ByVal wrkstnr As String, ByVal tnr As String, ByVal partnr As String, ByVal status As Integer, ByVal fromDate As Date, ByVal toDate As Date) As Brilliantech.Packaging.Data.FullPackageInfo() Implements packSvc.IPackProcess.GetPackageInfos
            Return MyBase.Channel.GetPackageInfos(pid, wrkstnr, tnr, partnr, status, fromDate, toDate)
        End Function
        
        Public Function GetItemsByPackageId(ByVal pId As String) As Brilliantech.Packaging.Data.PackageItem() Implements packSvc.IPackProcess.GetItemsByPackageId
            Return MyBase.Channel.GetItemsByPackageId(pId)
        End Function
        
        Public Function GetPackageStatus() As packSvc.EnumObject() Implements packSvc.IPackProcess.GetPackageStatus
            Return MyBase.Channel.GetPackageStatus
        End Function
        
        Public Function GetValidateItemsByPackageId(ByVal packageId As String) As Brilliantech.Packaging.Data.CustomValidate() Implements packSvc.IPackProcess.GetValidateItemsByPackageId
            Return MyBase.Channel.GetValidateItemsByPackageId(packageId)
        End Function
        
        Public Function GetValidateItemsByPartAndWrkst(ByVal partNr As String, ByVal wrkstnr As String) As Brilliantech.Packaging.Data.CustomValidate() Implements packSvc.IPackProcess.GetValidateItemsByPartAndWrkst
            Return MyBase.Channel.GetValidateItemsByPartAndWrkst(partNr, wrkstnr)
        End Function
        
        Public Function WorkstationExists(ByVal wrkstnr As String) As Boolean Implements packSvc.IPackProcess.WorkstationExists
            Return MyBase.Channel.WorkstationExists(wrkstnr)
        End Function
        
        Public Function ModifyPackage(ByVal pack As Brilliantech.Packaging.Data.SinglePackage) As packSvc.ServiceMessage Implements packSvc.IPackProcess.ModifyPackage
            Return MyBase.Channel.ModifyPackage(pack)
        End Function
    End Class
End Namespace
